[project]
name = "poker-coursework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "j-marino", email = "juliusmail007@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
]

[project.scripts]
poker-coursework = "poker_coursework:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
